import time,os,sys

def main():
    pageTitle = input("Project name:\n>>> ")
    os.system('cls')
    input("By pressing enter you agree to allow this tool to modify all the files in this folder to convert the build to a PWA. This may cause undesiered operation. The creator(s) of this program will not be held liable for damages. To cancel, push CTRL+C\n")
    os.system('cls')
    print("Creating PWA...\nDO NOT CLOSE THIS WINDOW\n")
    time.sleep(3)
    os.system("del /q /f index.html")
    manifest = open("manifest.json","w")
    manifest.write('{"name":"'+pageTitle+'","short_name":"'+pageTitle+'","start_url":"/index.html","display":"standalone","orientation":"portrait","icons":[{"src":"/Icon.jpg","type":"image/jpg","sizes":"512x512"}]}')
    manifest.close()
    serviceWorker = open("sw.js","w")
    serviceWorker.write("const cacheName = 'MyFancyCacheName_v1.1';self.addEventListener('fetch', (event) => {if (event.request.mode != 'hgfdhghgfnvfng') {event.respondWith(caches.open(cacheName).then((cache) => {return fetch(event.request.url).then((fetchedResponse) => {cache.put(event.request, fetchedResponse.clone());return fetchedResponse;}).catch(() => {return cache.match(event.request.url);});}));} else {return;}});")
    serviceWorker.close()
    html = open("index.html","w")
    html.write("html stuff")
    html.close()
    os.system('cls')
    time.sleep(0.5)
    print("Done!")
    time.sleep(1)
    os.system('cls')
    print("Success! Please refer to the README.md file for further instructions.")
    time.sleep(0.7)
    print("\n\nTerminating in 5 seconds...")
    time.sleep(5)
    sys.exit()

def init():
    os.system('cls')
    print("Unity PWA Creator by Reuben Schiopu\nLoading...")
    time.sleep(2)
    print("Ready!")
    time.sleep(0.7)
    os.system('cls')
    main()

init()